name: CI
on:
  push:
    branches: [main]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - name: Install modules
        run: |
          npm install pnpm -g
          pnpm install
      - name: Run Lint
        run: pnpm run lint
